apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: cis-gke-eks-aks-generic-image-5.1.1-vulnerability-scanning
spec:
  policyName: CIS-GKE-EKS-AKS-Generic-Image-5.1.1 - Ensure Image Vulnerability Scanning is enabled
  description: 'CIS Kubernetes Benchmark 5.1.1: Ensure Image Vulnerability Scanning using container registry scanning or a third-party provider'
  rationale: Container images may contain known vulnerabilities that can be exploited by attackers. Regular vulnerability scanning helps identify and remediate security issues before deployment.
  remediation: |
    Enable image vulnerability scanning in your container registry:
    
    For AWS ECR:
    aws ecr put-image-scanning-configuration --repository-name [repo] --image-scanning-configuration scanOnPush=true
    
    For Google GCR:
    gcloud services enable containerscanning.googleapis.com
    
    For Azure ACR:
    az acr task create --registry [registry-name] --name vulnerabilityscan
    
    Only deploy images that have passed vulnerability scanning.
  categories:
    - Security Best Practices
    - Vulnerability Management
    - Image Security
  lifecycleStages:
    - BUILD
    - DEPLOY
  eventSource: NOT_APPLICABLE
  severity: MEDIUM_SEVERITY
  policySections:
    - sectionName: Image Configuration
      policyGroups:
        - fieldName: Image Registry
          booleanOperator: AND
          values:
            - value: ".*"
  mitreAttackVectors:
    - tactic: TA0002
      techniques:
        - T1190
        - T1203
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false 