apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5.1.5-prevent-default-service-account
  annotations:
    policies.kyverno.io/title: CIS-5.1.5 - Prevent Default Service Account Usage
    policies.kyverno.io/category: Security Best Practices, CIS Kubernetes Benchmark
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, ServiceAccount
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      The default service account should not be used to ensure that rights granted to applications 
      can be more easily audited and reviewed. This policy validates that pods do not use the 
      default service account by checking the serviceAccountName field.
    cis.kubernetes.benchmark/control: "5.1.5"
    cis.kubernetes.benchmark/title: "Ensure that default service accounts are not actively used"
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: prevent-default-service-account
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: >-
          CIS-5.1.5: The default service account should not be used. 
          Please specify a dedicated service account for your application.
          Create a custom service account and reference it in the pod specification.
        pattern:
          spec:
            =(serviceAccountName): "!default"
    - name: prevent-empty-service-account
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: >-
          CIS-5.1.5: A service account must be explicitly specified. 
          The default service account should not be used implicitly.
          Please specify a dedicated service account for your application.
        pattern:
          spec:
            serviceAccountName: "?*"
    - name: prevent-default-service-account-automount
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: >-
          CIS-5.1.5: Pod is using default service account with automatic token mounting.
          Disable automountServiceAccountToken or use a dedicated service account.
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.serviceAccountName || 'default' }}"
              operator: Equals
              value: "default"
            - key: "{{ request.object.spec.automountServiceAccountToken || 'true' }}"
              operator: Equals
              value: "true"
