apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5.1.6-limit-service-account-token-mounting
  annotations:
    policies.kyverno.io/title: CIS-5.1.6 - Limit Service Account Token Mounting
    policies.kyverno.io/category: Security Best Practices, CIS Kubernetes Benchmark
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, ServiceAccount
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Service Account tokens should not be mounted in pods except where the workload 
      running in the pod explicitly needs to communicate with the API server. This policy 
      enforces that pods explicitly set automountServiceAccountToken to false unless they 
      have a proper annotation indicating API access is required.
    cis.kubernetes.benchmark/control: "5.1.6"
    cis.kubernetes.benchmark/title: "Ensure that Service Account Tokens are only mounted where necessary"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-explicit-token-mounting-decision
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: >-
          CIS-5.1.6: Service account token mounting must be explicitly configured. 
          Set automountServiceAccountToken to false unless API access is required.
          If API access is needed, add annotation 'security.kubernetes.io/api-access: required'.
        pattern:
          spec:
            automountServiceAccountToken: "?*"
    
    - name: validate-api-access-annotation
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: >-
          CIS-5.1.6: When service account token mounting is enabled, proper annotation is required.
          Add annotation 'security.kubernetes.io/api-access: required' to justify API access need.
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.automountServiceAccountToken || 'true' }}"
              operator: Equals
              value: "true"
            - key: "{{ request.object.metadata.annotations.\"security.kubernetes.io/api-access\" || '' }}"
              operator: NotEquals
              value: "required"
    
    - name: prevent-default-sa-with-token-mounting
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: >-
          CIS-5.1.6: Default service account should not be used with token mounting enabled.
          Use a dedicated service account when API access is required.
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.serviceAccountName || 'default' }}"
              operator: Equals
              value: "default"
            - key: "{{ request.object.spec.automountServiceAccountToken || 'true' }}"
              operator: Equals
              value: "true"
    
    - name: warn-implicit-token-mounting
      match:
        any:
        - resources:
            kinds:
            - Pod
      validate:
        message: >-
          CIS-5.1.6 WARNING: Implicit service account token mounting detected. 
          Consider explicitly setting automountServiceAccountToken to false for better security.
        pattern:
          spec:
            =(automountServiceAccountToken): "!null"

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5.1.6-service-account-token-best-practices
  annotations:
    policies.kyverno.io/title: CIS-5.1.6 - Service Account Token Best Practices
    policies.kyverno.io/category: Security Best Practices, CIS Kubernetes Benchmark
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: ServiceAccount
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Ensures service accounts follow best practices for token mounting by setting 
      automountServiceAccountToken to false by default unless specifically needed.
    cis.kubernetes.benchmark/control: "5.1.6"
    cis.kubernetes.benchmark/title: "Service Account Token Mounting Best Practices"
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: service-account-default-no-automount
      match:
        any:
        - resources:
            kinds:
            - ServiceAccount
      validate:
        message: >-
          CIS-5.1.6: Service accounts should explicitly set automountServiceAccountToken to false 
          unless they are specifically designed for workloads that need API access. 
          Add annotation 'security.kubernetes.io/api-access: "required"' if API access is needed.
        anyPattern:
        # Pattern 1: Service account explicitly disables automounting (recommended default)
        - automountServiceAccountToken: false
        # Pattern 2: Service account enables automounting AND has annotation justifying the need
        - automountServiceAccountToken: true
          metadata:
            annotations:
              security.kubernetes.io/api-access: "required" 