apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: compliance-dashboard

namespace: compliance-dashboard

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- route.yaml

commonLabels:
  app: compliance-dashboard
  project: kubernetes-compliance

images:
- name: compliance-dashboard
  newTag: latest

replicas:
- name: compliance-dashboard
  count: 2 